/** @format */

import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import QueryWrappper from "./QueryWrappper";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"], variable: "--manrope" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryWrappper>
        <body className={`${inter.className} ${manrope.variable}`}>
          {children}
        </body>
      </QueryWrappper>
    </html>
  );
}
